// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppendableResource } from "./AppendableResource";
import type { ResourceId } from "./ResourceId";
import type { UpdatableResource } from "./UpdatableResource";

export type EventVerb<ID, T, C> = { "type": "insert", "payload": AppendableResource<ID, T, C> } | { "type": "update", "payload": UpdatableResource<ID, T, C> } | { "type": "upsert", "payload": UpdatableResource<ID, T, C> } | { "type": "delete", "payload": ResourceId };