// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Location } from "./Location";

export interface UpdatableResource<I, T, C> { location: Location<I, C>, data: T, }